# Site
repository: sproogen/resume-theme
favicon: images/ai_icon.png

# Content configuration version
version: 2

# Personal info
name: Lorenzo Leuzzi
title: MSc Computer Science (AI)
email: leuzzi.lorenzo1@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lorenzoleuzzi1
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lorenzo.leu
linkedin_username: lorenzo-leuzzi-8415432b4
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/io.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Lorenzo Leuzzi, a Computer Science graduate specializing in Artificial Intelligence. With hands-on experience in deep learning, robotics, and data analysis, I’m passionate about applying AI to solve real-world challenges. My work spans research in machine learning, deep learning, continual learning and collective intelligence. I’m always looking for exciting opportunities abroad to expand my skills and gain new perspectives. Explore my projects to see how I combine technical skills with research and creative problem-solving.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Lifelong Evolutionary Swarms
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: International Exchange Student
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Swanville High School, Minnesota, USA
        caption: Sept 2017 - June 2018
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Erasmus+ Student (BSc)
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: International University of Struga, North Macedonia
        caption: Sept 2021 - Feb 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      
      - layout: left
        title: Curricular Traineeship
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Simaz – Lab. Di Ruberto @ University of Cagliari, Italy
        caption: Sept 2021 - Feb 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Erasmus+ Student (MSc)
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Universidad Politiecnica de Madrid, Spain
        caption: Sept 2023 - Feb 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Swarm Robotics Intern
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Bristol Robotics Laboratory, UK
        caption: Aug 2024 - Sept 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Cagliari
        caption: 2019 - 2022
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
          Gained a strong foundation in core concepts of informatics, including programming, algorithms, and software engineering.
          
          **GPA**: 4.0/4.0 with Honors (110/110 cum laude).
          
          **Coursework**: Programming, Algorithms, Data Structures, Software Engineering, Computer Architecture, Mathematical Analysis, Operating Systems, Databases, Web Technologies, and more.

          **Thesis**: *An Approach to Domain Generalization in the Field of Re-Identification*.


      - layout: left
        title: University of Pisa
        caption: 2022 - 2024
        sub_title: MSc Computer Science (AI)
        description: | # this will include new lines to allow paragraphs
          Specialized in Artificial Intelligence, focusing on advanced topics like machine learning, deep learning, and data mining.

          **GPA**: 4.0/4.0 with Honors (110/110 cum laude).
          
          **Coursework**: Machine Learning, Intelligent System for Pattern Recognition (Signal Processing, Generative Models, Deep Learning), Data Mining, Distributed and Parallel Systems, Startup Building, Smart Applications, Computation Mathematics for Learning and Data Analysis, Continual Learning, Human Languages Technologies, Information Retrieval, and more.

          **Thesis**: *Lifelong Evolutionary Swarms*.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Computer Science and Artificial Intelligence some of my other interests and hobbies are:
      - **Sports**: Played basketball on a team for several years, enjoy casual tennis, and recently started playing padel.
      - **Outdoor Activities**: Mainly hiking, with some occasional climbing.
      - **Painting**: Enjoy painting landscapes in an impressionist style, primarily using oil colors.
      - **Music**: Started with violin as a child, moved on to drumming and beat production, and now enjoy exploring new music as a listener.
      - **Always excited to do new experiences and learn new things**!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
